"""add many2many relationship

Revision ID: 3ba47fd77a
Revises: 46d632d1ada
Create Date: 2014-03-11 15:12:30.555019

"""

# revision identifiers, used by Alembic.
revision = '3ba47fd77a'
down_revision = '46d632d1ada'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    ### end Alembic commands ###
