"""add about_me and last_seen

Revision ID: 46d632d1ada
Revises: 52ba727c39e
Create Date: 2014-02-28 12:10:38.605954

"""

# revision identifiers, used by Alembic.
revision = '46d632d1ada'
down_revision = '52ba727c39e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    ### end Alembic commands ###
